USE [EMOS_WEB]
GO

/****** Object:  Table [dbo].[DMS_Marriage]    Script Date: 28.04.2015 14:48:56 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DMS_Marriage](
	[LocalSkid] [int] NOT NULL,
	[fk_ErpId] [int] NOT NULL,
 CONSTRAINT [PK_DMS_Marriage] PRIMARY KEY CLUSTERED 
(
	[LocalSkid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

