USE [EMOS_WEB]
GO

/****** Object:  Table [dbo].[DMS_MFP]    Script Date: 28.04.2015 14:49:02 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DMS_MFP](
	[MfpPos] [int] NOT NULL,
	[Description] [nvarchar](255) NULL,
	[fk_LocalSkidNr] [int] NULL,
 CONSTRAINT [PK_DMS_MFP] PRIMARY KEY CLUSTERED 
(
	[MfpPos] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

