//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dmspl.common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("dmspl.common.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script type=&quot;text/javascript&quot;&gt;
        ///// &lt;![CDATA[
        ///        function SHH(stl, clel) {
        ///            var elem = document.getElementsByClassName(stl);
        ///            var styl = &apos;&apos;;
        ///            if (elem[0].style.display == &apos;&apos;) {
        ///                styl = &apos;none&apos;;
        ///                clel.style.background = &quot;#FFA0A0&quot;;                
        ///            }
        ///            else {
        ///                clel.style.background = &quot;#A0FFA0&quot;;
        ///            }
        ///            for (i = 0; i &lt; elem.length; i++) {
        ///                elem[i].style.display = s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HTMLScript {
            get {
                return ResourceManager.GetString("HTMLScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;style  type=&quot;text/css&quot;&gt;
        ///body {
        ///    background-color: #505050;
        ///    text-align: center; 
        ///    font-family: &apos;Courier New&apos;;
        ///    font-size: small;
        ///}
        ///table {
        ///    width: 100%;
        ///    background-color: white;
        ///}
        ///th {
        ///    background-color: black;
        ///    color: white;
        ///    margin: 1px;
        ///    padding: 1px;
        ///}
        ///#wrap {
        ///    width: 100%;
        ///    position: absolute;
        ///    top: 0;
        ///    left: 0;
        ///}
        ///#dmenu {
        ///    margin: 0px;
        ///    width: 200px;
        ///    float:left;
        ///    position: absolute;
        ///    top: 8px;
        ///    left: -195px;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HTMLStyle {
            get {
                return ResourceManager.GetString("HTMLStyle", resourceCulture);
            }
        }
    }
}
